#' Fit multiple workflows with resampling for stacking
#'
#' @name h3sdm_fit_models_stack
#' @title Fit multiple workflows for model stacking
#' @description
#' Fits a set of tidymodels workflows using resampling with `fit_resamples()`
#' and `control_stack_resamples()` to generate objects suitable for stacking.
#' For each workflow, both the resampled model (`cv_model`) and the original
#' workflow are returned. This is intended as a helper function for creating
#' ensembles of multiple models in the `h3sdm` workflow.
#'
#' @param workflows A named list of tidymodels workflows. Each element should be a workflow object.
#' @param data_split A resampling object, e.g., generated by `rsample::vfold_cv()`.
#' @param presence_data (Optional) A data frame containing the data to fit the workflows on.
#'
#' @return A list with one element `models`. Each element of `models` is itself
#' a list with:
#'   - `cv_model`: the resampled model (`tune_results` object)
#'   - `workflow`: the original workflow object
#'
#' @examples
#' \dontrun{
#' # Example requires prepared workflows and resampling object:
#' # wfs <- list(random_forest = my_workflow_rf, glmnet = my_workflow_glm)
#' # scv <- rsample::vfold_cv(my_data, v = 5)
#' results <- h3sdm_fit_models_stack(workflows = wfs, data_split = scv)
#' results$models$random_forest$cv_model
#' results$models$random_forest$workflow
#' }
#'
#' @export


h3sdm_fit_models_stack <- function(workflows, data_split, presence_data = NULL) {

  # Inicializamos la lista que contendrá los resultados
  results <- list(models = list())

  # Iteramos sobre cada workflow
  for (mod_name in names(workflows)) {
    wf <- workflows[[mod_name]]

    # Ajuste usando fit_resamples con control_stack_resamples
    res <- fit_resamples(
      wf,
      resamples = data_split,
      control = stacks::control_stack_resamples()
    )

    # Guardamos tanto el workflow como el objeto resample (cv_model)
    results$models[[mod_name]] <- list(
      cv_model = res,
      workflow = wf
    )
  }

  return(results)
}
