#' Fit multiple workflows with resampling for stacking
#'
#' @name h3sdm_fit_models_stack
#' @title Fit multiple workflows for model stacking
#' @description
#' Fits a set of tidymodels workflows using resampling with `fit_resamples()`
#' and `control_stack_resamples()` to generate objects suitable for stacking.
#' For each workflow, both the resampled model (`cv_model`) and the original
#' workflow are returned. This is intended as a helper function for creating
#' ensembles of multiple models in the `h3sdm` workflow.
#'
#' @param wfs A named list of tidymodels workflows. Each element should be a workflow object.
#' @param scv A resampling object, e.g., generated by `rsample::vfold_cv()`.
#' @param datos_presencia A data frame containing the data to fit the workflows on.
#'
#' @return A list with one element `models`. Each element of `models` is itself
#' a list with:
#'   - `cv_model`: the resampled model (`tune_results` object)
#'   - `workflow`: the original workflow object
#'
#' @examples
#' \dontrun{
#' # Assuming you have workflows 'wfs' and a spatial CV object 'scv'
#' results <- h3sdm_fit_models_stack(wfs, scv, datos_presencia)
#' results$models$random_forest$cv_model
#' results$models$random_forest$workflow
#' }
#'
#' @export

h3sdm_fit_models_stack <- function(workflows, data_split, presence_data = NULL) {

  # Inicializamos la lista que contendrá los resultados
  results <- list(models = list())

  # Iteramos sobre cada workflow
  for(mod_name in names(wfs)) {
    wf <- wfs[[mod_name]]

    # Ajuste usando fit_resamples con control_stack_resamples
    res <- fit_resamples(
      wf,
      resamples = scv,
      control = stacks::control_stack_resamples()
    )

    # Guardamos tanto el workflow como el objeto resample (cv_model)
    results$models[[mod_name]] <- list(
      cv_model = res,
      workflow = wf
    )
  }

  return(results)
}
